name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - run: npm run install:all
      - run: npm run test:component
